### ISSUE TITLE
MSAcpi_ThermalZoneTemperature undefined

### ISSUE THREAD

**Issue by riazXrazor** [jpgrusling/node-wmi#11]
it returns undefined any idea y ?

wmi.Query({
    class: 'MSAcpi_ThermalZoneTemperature',
    namespace : 'root/wmi'
  }, function(err, data) {
     console.log(data);
  });

**Comment by MadbHatter** [comment]
Wrong namespace. root\cimv2 (Standard) is the right one.

**Comment by riazXrazor** [comment]
@MadbHatter still undefined :( ,   
although m using open hardware monitor to get the hardware details

**Comment by MadbHatter** [comment]
Download the WMI Explorer (Just google it) and use it to find your class/properties.
Also Instead of "MSAcpi_ThermalZoneTemperature" use "Win32_TemperatureProbe".
________________________________

**Comment by NicolaiVdS** [comment]
@riazXrazor You need to have 2 back slashes 
example `root\\WMI`
