### ISSUE TITLE
charset problem

### ISSUE THREAD

**Issue by rwson** [jpgrusling/node-wmi#12]
I use this module in the virtual machine to get garbled operating system information, but it is normal to use native wmi statements.

![28bd62ec-8221-4831-b2d4-9ef5722d5d39](https://user-images.githubusercontent.com/9476421/40340565-253a2946-5db2-11e8-925b-115a3e429e2a.png)
<img width="741" alt="qq20180522-110140 2x" src="https://user-images.githubusercontent.com/9476421/40340567-2585c18a-5db2-11e8-8e5a-f07d73eaafdd.png">

**Comment by liuyiseaduncom** [comment]
Query.js中280行标准输出流读取的data数据不能直接累加，添加以下处理：
![image](https://user-images.githubusercontent.com/41336266/42823430-14579e6c-8a10-11e8-81aa-2f02765ff9c8.png)

**Comment by liuyiseaduncom** [comment]
Query.js中280行标准输出流读取的data数据不能直接累加，添加以下处理：
![image](https://user-images.githubusercontent.com/41336266/42823504-4bb16ba4-8a10-11e8-9daf-c959f9d2898e.png)

**Comment by rwson** [comment]
I forked this repository to fixed this problem and published a new npm package called[wmi-client-chinese](https://www.npmjs.com/package/wmi-client-chinese)
